#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'legoBlocks' function below.
#
# The function is expected to return an INTEGER.
# The function accepts following parameters:
#  1. INTEGER n
#  2. INTEGER m
#

def legoBlocks(n, m):
    mod =10**9+7
    f1 = [1] + [0] * m
    fn = [1] + [0] * m
    for i in range(1, m + 1):
        f1[i] = sum(f1[max(0, i - 4) : i]) % mod
        fn[i] = f1[i] ** n % mod
    
    gn = [1] + [0] * m
    for i in range(1, m + 1):
        gn[i] = fn[i]
        for j in range(1, i):
            gn[i] -= gn[j] * fn[i - j] % mod
        gn[i] %= mod
        
    return (gn[m] + mod) % mod

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    t = int(input().strip())

    for t_itr in range(t):
        first_multiple_input = input().rstrip().split()

        n = int(first_multiple_input[0])

        m = int(first_multiple_input[1])

        result = legoBlocks(n, m)

        fptr.write(str(result) + '\n')

    fptr.close()
